In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [11]:
np.array(mylist)

array([1, 2, 3])

In [12]:
arr = np.array(mylist)

In [13]:
arr

array([1, 2, 3])

In [12]:
mylist

[1, 2, 3]

In [13]:
type(myarr)

numpy.ndarray

In [14]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

In [21]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [22]:
len(np.arange(0,101,20))

6

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

The dot indicates that the elements of the array are floating points

In [33]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [23]:
np.linspace(0,10,10+1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

arg1 = startpoint

arg2 = endpoint

arg3 = how many numbers in between (endpoint in included). Uneven steps generate easy readable numbers.

In [24]:
len(np.linspace(0,10,10+1))

11

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.random.rand(3)

array([0.83003331, 0.84469018, 0.88080682])

Uniform distribution. np.random.rand cannot return 1. we can also set seeds.

In [37]:
np.random.rand(3,2)

array([[0.65579236, 0.53521399],
       [0.35973832, 0.17424204],
       [0.6555724 , 0.31038606]])

In [38]:
np.random.randn()

1.468023645616841

Samples of standard normal disribution with mean 0 and variance 1.

In [42]:
np.random.randint(1,11,(3,5))

array([[9, 5, 6, 7, 7],
       [2, 8, 7, 8, 1],
       [2, 7, 4, 6, 6]])

Uniform distribution

arg1 = lower threshold

arg2 = higher threshold (exclusive)

In [44]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

Allows you to reproduce results

In [46]:
arr = np.arange(0,25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
arrmatrix = arr.reshape(5,5)

In [72]:
arrmatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
random_arr = np.random.randint(0,10,10)

In [64]:
random_arr

array([9, 5, 8, 0, 9, 2, 6, 3, 8, 2])

In [65]:
random_arr.max()

9

In [66]:
random_arr.argmax()

0

Gives back the index location. Note that the arrays are zero-indexed.

In [67]:
random_arr.min()

0

In [68]:
random_arr.argmin()

3

In [69]:
random_arr.dtype

dtype('int64')

In [70]:
arr.shape

(25,)

In [74]:
arrmatrix.shape

(5, 5)

Reshaping

In [76]:
smallarr = np.random.randint(0,10,3)
smallarr

array([4, 8, 6])

In [77]:
smallarr.reshape(1,3)

array([[4, 8, 6]])

In [78]:
smallarr.reshape(3,1)

array([[4],
       [8],
       [6]])

The two latter reshapes are matrices (note the number of square brackets)