In [1]:
import numpy as np

In [65]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[0]

0

In [4]:
arr[0:2]

array([0, 1])

Reads "return array starting from arg1 and up to -but not including- arg2"

If we omit arg1, we start at the beginning of the array. Equivalent to setting arg1 = 0

If we omit arg2, we go end of the array. Equivalent to setting arg2 = len(array)

In [6]:
arr[:2]

array([0, 1])

In [7]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[2:len(arr)]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
len(arr)

11

In [59]:
arr[:]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [58]:
arr2 = arr

# arr2 acts as a pointer to arr!
# to create a copy of the array use the copy method 
# arr_copy = arr.copy()

arr2[0:5] = 100
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Slicing section of an array and setting it to a new variable only acts as a pointer to the original array

In [60]:
slice_arr = arr[0:3]
slice_arr

array([100, 100, 100])

In [61]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99])

In [62]:
arr

array([ 99,  99,  99, 100, 100,   5,   6,   7,   8,   9,  10])

In [69]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
matrix.shape

(3, 3)

In [94]:
len(matrix)

3

In [73]:
matrix[0]
# first row

array([0, 1, 2])

In [74]:
matrix[2]
# last row

array([6, 7, 8])

In [77]:
matrix[0,0]
# or matrix[0][0]

0

In [80]:
matrix[:2,:2]

array([[0, 1],
       [3, 4]])

In [86]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [88]:
arr[bool_arr]
# alternatively we can skip the reassigment with arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [99]:
matrix2 = np.ones((9,5))
matrix2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [100]:
len(matrix2)

9