In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [11]:
np.array(mylist)

array([1, 2, 3])

In [12]:
arr = np.array(mylist)

In [13]:
arr

array([1, 2, 3])

In [12]:
mylist

[1, 2, 3]

In [13]:
type(myarr)

numpy.ndarray

In [14]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

In [21]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [22]:
len(np.arange(0,101,20))

6

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

The dot indicates that the elements of the array are floating points

In [33]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [23]:
np.linspace(0,10,10+1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

arg1 = startpoint

arg2 = endpoint

arg3 = how many numbers in between (endpoint in included). Uneven steps generate easy readable numbers.

In [24]:
len(np.linspace(0,10,10+1))

11

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.random.rand(3)

array([0.83003331, 0.84469018, 0.88080682])

Uniform distribution. np.random.rand cannot return 1. we can also set seeds.

In [37]:
np.random.rand(3,2)

array([[0.65579236, 0.53521399],
       [0.35973832, 0.17424204],
       [0.6555724 , 0.31038606]])

In [38]:
np.random.randn()

1.468023645616841

Samples of standard normal disribution with mean 0 and variance 1.

In [42]:
np.random.randint(1,11,(3,5))

array([[9, 5, 6, 7, 7],
       [2, 8, 7, 8, 1],
       [2, 7, 4, 6, 6]])

Uniform distribution

arg1 = lower threshold

arg2 = higher threshold (exclusive)

In [44]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

Allows you to reproduce results

In [46]:
arr = np.arange(0,25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
arrmatrix = arr.reshape(5,5)

In [72]:
arrmatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
random_arr = np.random.randint(0,10,10)

In [64]:
random_arr

array([9, 5, 8, 0, 9, 2, 6, 3, 8, 2])

In [65]:
random_arr.max()

9

In [66]:
random_arr.argmax()

0

Gives back the index location. Note that the arrays are zero-indexed.

In [67]:
random_arr.min()

0

In [68]:
random_arr.argmin()

3

In [69]:
random_arr.dtype

dtype('int64')

In [70]:
arr.shape

(25,)

In [74]:
arrmatrix.shape

(5, 5)

Reshaping

In [76]:
smallarr = np.random.randint(0,10,3)
smallarr

array([4, 8, 6])

In [77]:
smallarr.reshape(1,3)

array([[4, 8, 6]])

In [78]:
smallarr.reshape(3,1)

array([[4],
       [8],
       [6]])

The two latter reshapes are matrices (note the number of square brackets)

In [1]:
import numpy as np

In [65]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[0]

0

In [4]:
arr[0:2]

array([0, 1])

Reads "return array starting from arg1 and up to -but not including- arg2"

If we omit arg1, we start at the beginning of the array. Equivalent to setting arg1 = 0

If we omit arg2, we go end of the array. Equivalent to setting arg2 = len(array)

In [6]:
arr[:2]

array([0, 1])

In [7]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[2:len(arr)]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
len(arr)

11

In [59]:
arr[:]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [58]:
arr2 = arr

# arr2 acts as a pointer to arr!
# to create a copy of the array use the copy method 
# arr_copy = arr.copy()

arr2[0:5] = 100
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Slicing section of an array and setting it to a new variable only acts as a pointer to the original array

In [60]:
slice_arr = arr[0:3]
slice_arr

array([100, 100, 100])

In [61]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99])

In [62]:
arr

array([ 99,  99,  99, 100, 100,   5,   6,   7,   8,   9,  10])

In [69]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
matrix.shape

(3, 3)

In [94]:
len(matrix)

3

In [73]:
matrix[0]
# first row

array([0, 1, 2])

In [74]:
matrix[2]
# last row

array([6, 7, 8])

In [77]:
matrix[0,0]
# or matrix[0][0]

0

In [80]:
matrix[:2,:2]

array([[0, 1],
       [3, 4]])

In [86]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [88]:
arr[bool_arr]
# alternatively we can skip the reassigment with arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [99]:
matrix2 = np.ones((9,5))
matrix2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [100]:
len(matrix2)

9

In [2]:
import numpy as np

In [4]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [7]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
2*arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr / arr

<ipython-input-11-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
1 / arr

<ipython-input-12-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
np.log(arr)

<ipython-input-15-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [17]:
arr.sum()

45

In [18]:
arr.mean()

4.5

In [20]:
arr.max()

9

In [21]:
arr.var()

8.25

In [22]:
arr.std()

2.8722813232690143

In [27]:
arr2 = np.arange(0,25).reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr2.sum()

300

In [33]:
arr2.sum(axis=0)
# means perform the operation accross the rows
# -> output is an array with the sum of the elements of the columns

array([50, 55, 60, 65, 70])

In [34]:
arr2.sum(axis=1)
# means perform the operation accross the columns
# -> output is an array with the sum of the elements of the rows

array([ 10,  35,  60,  85, 110])