In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../prep-data/Advertising.csv")

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

---

# Intro to CV

In [4]:
X = df.drop('sales',axis=1)

In [5]:
y = df['sales']

---

## Train | Test Split

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

---

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(X_train)

StandardScaler()

In [11]:
X_train = scaler.transform(X_train)

In [12]:
X_test = scaler.transform(X_test)

---

In [13]:
from sklearn.linear_model import Ridge

In [14]:
model = Ridge(alpha=100)

In [15]:
model.fit(X_train,y_train)

Ridge(alpha=100)

In [16]:
y_pred = model.predict(X_test)

---

In [17]:
from sklearn.metrics import mean_squared_error

In [18]:
mean_squared_error(y_test, y_pred)

7.834988593141581

---

In [19]:
model2 = Ridge(alpha=1)

In [20]:
model2.fit(X_train,y_train)

Ridge(alpha=1)

In [21]:
y_pred2 = model2.predict(X_test)

In [22]:
mean_squared_error(y_test, y_pred2)

3.7310152520189783

---

In [23]:
from sklearn.metrics import mean_squared_error

In [24]:
mean_squared_error(y_test, y_pred2)
# note that the model performs better with this alpha value

3.7310152520189783

## Train | Validation | Test Split
---

In [25]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [26]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_vt, y_train, y_vt = train_test_split(X, y, test_size=0.3, random_state=42)

In [29]:
X_val, X_test, y_val, y_test = train_test_split(X_vt, y_vt, test_size=0.5, random_state=42)

In [30]:
# X -> X_train, X_val, X_test
# y -> y_train, y_val, y_test
print(f"len(X_train)={len(X_train)}, len(X_val)={len(X_val)}, len(X_test)={len(X_test)}")

len(X_train)=140, len(X_val)=30, len(X_test)=30


In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaler = StandardScaler()

In [33]:
scaler.fit(X_train)

StandardScaler()

In [34]:
X_train = scaler.transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

In [35]:
from sklearn.linear_model import Ridge

In [36]:
model1 = Ridge(alpha=100)

In [37]:
model1.fit(X_train,y_train)

Ridge(alpha=100)

In [38]:
y_val_pred = model.predict(X_val)

In [39]:
from sklearn.metrics import mean_squared_error

In [40]:
mean_squared_error(y_val, y_val_pred)

7.159820078783062

In [41]:
model2 = Ridge(alpha=1)

In [42]:
model2.fit(X_train,y_train)

Ridge(alpha=1)

In [43]:
y_val_pred2 = model2.predict(X_val)

In [44]:
mean_squared_error(y_val, y_val_pred2)

2.5522105291435984

### Final Performance Evaluation

In [45]:
y_test_pred = model2.predict(X_test)

In [46]:
mean_squared_error(y_test, y_test_pred)

5.048154486831445

# Built-In Function

In [47]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [48]:
X = df.drop('sales',axis=1)

In [49]:
y = df['sales']

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
scaler = StandardScaler()

In [54]:
scaler.fit(X_train)

StandardScaler()

In [55]:
X_train = scaler.transform(X_train)

In [56]:
X_test = scaler.transform(X_test)

In [57]:
model = Ridge(alpha=100)

---

In [58]:
from sklearn.model_selection import cross_val_score

In [59]:
scores = cross_val_score(model,X_train,y_train, scoring='neg_mean_squared_error',cv=5)

In [60]:
scores

array([-8.24238361, -4.92683375, -8.23406926, -8.57882398, -8.86803785])

In [61]:
abs(scores.mean())

7.770029691272373

In [62]:
model2 = Ridge(alpha=1)

In [63]:
scores2 = cross_val_score(model2,X_train,y_train, scoring='neg_mean_squared_error',cv=5)

In [64]:
scores2

array([-2.32283992, -1.27714646, -2.73414356, -2.19155235, -5.11459617])

In [65]:
abs(scores2.mean())
# this model performs better with alpha is equal to one with a mean error of 2.7 in a 5-fold cross-validation

2.728055693070764

In [66]:
model2.fit(X_train, y_train)

Ridge(alpha=1)

In [67]:
y_pred = model2.predict(X_test)

In [68]:
mean_squared_error(y_test, y_pred)

3.7310152520189783

---

In [69]:
# Create X and y
X = df.drop('sales',axis=1)
y = df['sales']

# Split the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# Scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [70]:
from sklearn.model_selection import cross_validate

In [71]:
model = Ridge(alpha=100)

In [72]:
scores = cross_validate(model, X_train, y_train,
                       scoring=['neg_mean_squared_error','neg_mean_absolute_error'],cv=10)

In [73]:
scores

{'fit_time': array([0.00191689, 0.00256705, 0.00255275, 0.00141311, 0.00308609,
        0.00202179, 0.00088286, 0.00114298, 0.00180507, 0.00099993]),
 'score_time': array([0.00153899, 0.00126696, 0.0015862 , 0.00117397, 0.00133491,
        0.00225902, 0.00064898, 0.00118399, 0.00092077, 0.00116301]),
 'test_neg_mean_squared_error': array([ -6.06067062, -10.62703078,  -3.99342608,  -5.00949402,
         -9.14179955, -13.08625636,  -3.83940454,  -9.05878567,
         -9.05545685,  -5.77888211]),
 'test_neg_mean_absolute_error': array([-1.8102116 , -2.54195751, -1.46959386, -1.86276886, -2.52069737,
        -2.45999491, -1.45197069, -2.37739501, -2.44334397, -1.89979708])}

In [74]:
scores = pd.DataFrame(scores)

In [75]:
scores

fit_time  score_time  test_neg_mean_squared_error  \
0  0.001917    0.001539                    -6.060671   
1  0.002567    0.001267                   -10.627031   
2  0.002553    0.001586                    -3.993426   
3  0.001413    0.001174                    -5.009494   
4  0.003086    0.001335                    -9.141800   
5  0.002022    0.002259                   -13.086256   
6  0.000883    0.000649                    -3.839405   
7  0.001143    0.001184                    -9.058786   
8  0.001805    0.000921                    -9.055457   
9  0.001000    0.001163                    -5.778882   

   test_neg_mean_absolute_error  
0                     -1.810212  
1                     -2.541958  
2                     -1.469594  
3                     -1.862769  
4                     -2.520697  
5                     -2.459995  
6                     -1.451971  
7                     -2.377395  
8                     -2.443344  
9                     -1.899797

In [76]:
scores.mean()

fit_time                        0.001839
score_time                      0.001308
test_neg_mean_squared_error    -7.565121
test_neg_mean_absolute_error   -2.083773
dtype: float64

In [77]:
model = Ridge(alpha=1)

In [78]:
scores = cross_validate(model, X_train, y_train,
                       scoring=['neg_mean_squared_error','neg_mean_absolute_error'],cv=10)

In [79]:
scores = pd.DataFrame(scores)

In [80]:
scores

fit_time  score_time  test_neg_mean_squared_error  \
0  0.001801    0.003917                    -2.962508   
1  0.006503    0.003248                    -3.057378   
2  0.001346    0.003832                    -2.173740   
3  0.002360    0.001197                    -0.833034   
4  0.001962    0.001298                    -3.464018   
5  0.006119    0.001634                    -8.232647   
6  0.001317    0.000835                    -1.905864   
7  0.001197    0.000797                    -2.765048   
8  0.004080    0.004103                    -4.989505   
9  0.002246    0.001272                    -2.846438   

   test_neg_mean_absolute_error  
0                     -1.457174  
1                     -1.555308  
2                     -1.238770  
3                     -0.768938  
4                     -1.434489  
5                     -1.494316  
6                     -1.081362  
7                     -1.250011  
8                     -1.580971  
9                     -1.223326

In [81]:
scores.mean()

fit_time                        0.002893
score_time                      0.002213
test_neg_mean_squared_error    -3.323018
test_neg_mean_absolute_error   -1.308467
dtype: float64

In [82]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [83]:
y_pred = model.predict(X_test)

In [84]:
mean_squared_error(y_test, y_pred)

2.319021579428752

In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [86]:
df = pd.read_csv('../prep-data/Advertising.csv')

In [87]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [88]:
## CREATE X and y
X = df.drop('sales',axis=1)
y = df['sales']

# TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# SCALE DATA
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [105]:
from sklearn.linear_model import ElasticNet
# two important hyperparameters: l1_ratio and alpha -> what is the optimal l1_ratio and alpha value

In [106]:
base_model = ElasticNet()

In [116]:
p_grid = {
    'alpha':[.1,1,5,10,50,100],
    'l1_ratio':[.1,.5,.7,.95,.99,1]
}

In [117]:
from sklearn.model_selection import GridSearchCV

In [118]:
grid_model = GridSearchCV(
    estimator=base_model,
    param_grid =p_grid, 
    scoring='neg_mean_squared_error',
    cv=5, 
    verbose=1
)

In [119]:
grid_model.fit(X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 180 out of 180 | elapsed:    0.4s finished


GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.5, 0.7, 0.95, 0.99, 1]},
             scoring='neg_mean_squared_error', verbose=1)

In [120]:
grid_model.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=1)

In [121]:
grid_model.best_params_

{'alpha': 0.1, 'l1_ratio': 1}

In [101]:
grid_model.predict(X_test)

array([15.66368907, 19.46408313, 11.5334467 , 16.90361792,  9.28986377,
        7.20512596, 20.12630114, 17.21717961,  9.92059194, 19.08401429,
       12.41632064, 13.90812112, 13.77020299, 21.0764028 , 18.3144613 ,
       10.08244137, 15.55332779,  7.8863488 ,  7.74187755, 20.22579399,
        7.95632931, 18.1169614 , 24.38514439, 22.58250106,  8.15339222,
       12.73095252, 21.27373859,  8.23268934, 12.49004679, 12.52397252,
       10.85578463, 19.10783619, 10.20239152,  6.91681664, 17.22447596,
        7.96982919,  9.39929572,  8.45480843, 10.65442906, 10.75772226,
       13.04497384,  9.92194633, 10.33480469,  8.21121593, 11.62693221,
       10.19036614,  9.11221   , 16.22496113, 13.29734786, 20.61601005,
       12.51850026, 14.00017552, 17.50249596, 11.23188839, 12.64040529,
        5.74152682, 23.02575646, 12.62656713, 18.65905383, 15.16774331])

In [97]:
pd.DataFrame(grid_model.cv_results_).head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.001503      0.000639         0.000846        0.000467         0.1   
1       0.001114      0.000158         0.000588        0.000146         0.1   
2       0.001480      0.000492         0.000816        0.000498         0.1   
3       0.001057      0.000211         0.000614        0.000382         0.1   
4       0.003099      0.001911         0.000847        0.000078         0.1   

  param_l1_ratio                            params  split0_test_score  \
0            0.1   {'alpha': 0.1, 'l1_ratio': 0.1}          -3.453021   
1            0.5   {'alpha': 0.1, 'l1_ratio': 0.5}          -3.325440   
2            0.7   {'alpha': 0.1, 'l1_ratio': 0.7}          -3.269880   
3           0.95  {'alpha': 0.1, 'l1_ratio': 0.95}          -3.213052   
4           0.99  {'alpha': 0.1, 'l1_ratio': 0.99}          -3.208124   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0          -1.405190          -5.789125          -2.187302          -4.645576   
1          -1.427522          -5.595610          -2.163089          -4.451679   
2          -1.442432          -5.502437          -2.163950          -4.356738   
3          -1.472417          -5.396258          -2.177452          -4.241080   
4          -1.478489          -5.380242          -2.181097          -4.222968   

   mean_test_score  std_test_score  rank_test_score  
0        -3.496043        1.591601                6  
1        -3.392668        1.506827                5  
2        -3.347088        1.462765                4  
3        -3.300052        1.406248                3  
4        -3.294184        1.396953                2

In [98]:
y_pred = grid_model.predict(X_test)

In [99]:
from sklearn.metrics import mean_squared_error

In [100]:
mean_squared_error(y_test, y_pred)

2.387342642087474