In [1]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [10]:
myarr = np.array(mylist)

In [11]:
myarr

array([1, 2, 3])

In [12]:
mylist

[1, 2, 3]

In [13]:
type(myarr)

numpy.ndarray

In [20]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [21]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [29]:
len(np.arange(0,100,2))

50

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [39]:
np.linspace(0,10,10+1)
# a third argument in this form makes a humanly readable output / linear space

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])